### ISSUE TITLE
Vision Camera V4

### ISSUE THREAD

**Issue by DeanGracey** [gev2002/react-native-vision-camera-v3-pose-detection#3]
Hi, I'm still trying to wrap my head around these plugins and how they interact with vision camera. 

It looks like you've updated at least one of your other packages to support this format: 

import React from 'react';
import { StyleSheet } from "react-native";
import {
  Camera,
  useCameraDevice,
  useFrameProcessor,
} from "react-native-vision-camera";
import { useTextRecognition } from "react-native-vision-camera-v3-text-recognition";

function App() {
  const device = useCameraDevice('back');
  const options = { language : 'latin' }
  const {scanText} = useTextRecognition(options)
  const frameProcessor = useFrameProcessor((frame) => {
    'worklet'
    const data = scanText(frame)
	console.log(data, 'data')
  }, [])
  return (
      <>
      {!!device && (
        <Camera
          style={StyleSheet.absoluteFill}
          device={device}
          isActive
          frameProcessor={frameProcessor}
        />
      )}
      </>
  );
}
export default App;

Does this mean that one could then replace the usage of useFrameProcessor with the new useSkiaFrameProcessor to draw results directly onto the camera (and thus allow the default recording to also record the drawn parts?). If so, could you please also update this package to follow the updated format of your text recognition package?

**Comment by gev2002** [comment]
Hi, sorry for the long wait, I can make a format like OCR package and use useSkiaFrameProcessors but I don't have free time to do it now. Also if your app needs to use useSkiaFrameProcessors I will somehow find time to implement it if you can sponsor me.
