### ISSUE TITLE
frame.render()

### ISSUE THREAD

**Issue by TheWeeezel** [gev2002/react-native-vision-camera-v3-pose-detection#6]
I cant get frame render to work currently.

Poses are detected but i cant see any drawings on the frame.

**Comment by gev2002** [comment]
Hi, Skia Frame Process works with Vision Camera V4 or higher. This package is for Vision Camera V3 and it is logical that it will not work.
You can sponsor me if you need a package that works with skia frame processors, you can write me about it to my gmail <a href="mailto:gev.avet.02@gmail.com">gev.avet.02@gmail.com</a>
